### ISSUE TITLE
Scheinbar gab es eine Aktualisierung.

### ISSUE THREAD

**Issue by Roughtrade** [chriszero/tvspielfilm2xmltv#14]
Ich bekomme seit heute leider folgenden Fehler:
09:05:06 ERROR::tvspielfilm2xmltv:
TypeError("'NoneType' object is not iterable",)
Traceback (most recent call last):
  File "/usr/local/bin/tvspielfilm2xmltv", line 134, in main
    grabber.start_grab()
  File "/usr/local/share/tvspielfilm2xmltv/tvsp2xmltv/tvsGrabber.py", line 74, in start_grab
    self.__grab_day(day, tvsp_id, chan_id)
  File "/usr/local/share/tvspielfilm2xmltv/tvsp2xmltv/tvsGrabber.py", line 90, in __grab_day
    for s in data:
TypeError: 'NoneType' object is not iterable

In der Hoffnung auf einen Fix 
Mit besten Grüßen

**Comment by chriszero** [comment]
Mehr Infos, Aufrufparameter, Configs

**Comment by Roughtrade** [comment]
Das läuft bei mir via cronjob auf meiner Diskstation und wird über scp an meinen Raspberry mit kodi geschickt:

#!/bin/sh
tvspielfilm2xmltv 2 '' 1 ard.de zdf.de rtl.de prosieben.de sat1.de vox.de kabel1.de rtl2.de superrtl.de sport1.de dmax.de sixx.de prosieben-maxx.de tele5.de 3sat.de arte.de phoenix.de ndr-hh.de mdr-thueringen.de wdr-dortmund.de bayern3.de hessen3.de rbb-brandenburg.de rtl-nitro.de zdfneo.de sat1-gold.de tagesschau24.de einsfestival.de zdfinfo.de ard-alpha.de nickelodeon.de

sed -i 's!file:///var/lib/epgsources!/storage/downloads/epg!'g /var/lib/epgsources/tvspielfilm2xmltv.xmltv
sed -i 's!rbb-brandenburg.de!rbb.de!'g /var/lib/epgsources/tvspielfilm2xmltv.xmltv
sed -i 's!mdr-thueringen.de!mdr.de!'g /var/lib/epgsources/tvspielfilm2xmltv.xmltv
sed -i 's!wdr-dortmund.de!wdr.de!'g /var/lib/epgsources/tvspielfilm2xmltv.xmltv
sed -i 's!ndr-hh.de!ndr.de!'g /var/lib/epgsources/tvspielfilm2xmltv.xmltv
sed -i 's!>NDR-HH<!>NDR<!'g /var/lib/epgsources/tvspielfilm2xmltv.xmltv
sed -i 's!>WDR-DO<!>WDR<!'g /var/lib/epgsources/tvspielfilm2xmltv.xmltv
sed -i 's!>RBB-BB<!>RBB<!'g /var/lib/epgsources/tvspielfilm2xmltv.xmltv
sed -i 's!>MDR-TH<!>MDR<!'g /var/lib/epgsources/tvspielfilm2xmltv.xmltv


scp -B /var/lib/epgsources/tvspielfilm2xmltv.xmltv root@192.168.1.137:/storage/downloads/epg/

scp -B /var/lib/epgsources/tvspielfilm2xmltv-img/*.* root@192.168.1.137:/storage/downloads/epg/tvspielfilm2xmltv-img/

**Comment by Roughtrade** [comment]
Der Fehler tritt bei ndr-hh.de auf. Habe zum Testen nur ARD und ZDF abgerufen, da geht es ohne Fehler.
